name: country_picker
description: A flutter package to select a country from a list of countries.

version: 2.0.21

homepage: https://github.com/Daniel-Ioannou
repository: https://github.com/Daniel-Ioannou/flutter_country_picker

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  collection:
  universal_io:
  flutter:
    sdk: flutter

flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.2
